// Generated by CoffeeScript 1.6.3
var User;

User = (function() {
  function User(api) {
    this.api = api;
    console.log("User::constructor called.");
  }

  User.prototype.create = function() {
    console.log("User::create called.");
    return this.api.request();
  };

  User.prototype["delete"] = function() {
    console.log("User::delete called.");
    return this.api.request();
  };

  User.prototype.get = function() {
    console.log("User::get called.");
    return this.api.request();
  };

  User.prototype.list = function() {
    console.log("User::list called.");
    return this.api.request();
  };

  User.prototype.update = function() {
    console.log("User::update called.");
    return this.api.request();
  };

  User.prototype.self = function(callback) {
    var options, route;
    console.log("User::self called.");
    route = '/user';
    options = {};
    return this.api.request(route, options, callback);
  };

  return User;

})();

module.exports = User;
