// Generated by CoffeeScript 1.6.3
var Api, Merchant, User, _;

_ = require('underscore');

Merchant = require('./api/merchant');

User = require('./api/user');

Api = (function() {
  function Api(client) {
    this.client = client;
    console.log("Api::constructor called.");
    this.user = new User(this);
    this.merchant = new Merchant(this);
  }

  Api.prototype.request = function(route, options, callback) {
    var body, config, headers;
    console.log("Api::request called.");
    console.log(this.client.token);
    if (!this.client.token) {
      throw new Error('Api is not ready');
    }
    headers = options.headers != null ? _.defaults(options.headers, this.client.headers) : _.defaults({}, this.client.headers);
    headers['Authorization'] = "Bearer " + this.client.token;
    options = _.defaults(options, this.client.options);
    body = options.body != null ? JSON.stringify(body) : null;
    config = {
      host: options.host,
      path: "" + options.path + options.api_version + route,
      method: options.method,
      port: this.client.port(),
      headers: headers,
      body: body
    };
    return this.client.raw_request(config, callback);
  };

  return Api;

})();

module.exports = Api;
